export const sampleRecipes = [
  {
    title: 'Avocado & Poached Egg Sourdough',
    description: 'Crisp toasted artisan sourdough topped with creamy mashed avocado, perfectly runny poached eggs, red pepper flakes, and microgreens.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80',
    category: 'Breakfast',
    tags: ['Vegetarian', 'High Protein', 'Quick Meals', 'Healthy'],
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Sourdough Bread', quantity: 2, unit: 'slices' },
      { name: 'Ripe Avocado', quantity: 1, unit: 'pieces' },
      { name: 'Fresh Eggs', quantity: 2, unit: 'pieces' },
      { name: 'Lemon Juice', quantity: 1, unit: 'tbsp' },
      { name: 'Red Pepper Flakes', quantity: 0.5, unit: 'tsp' },
      { name: 'Salt', quantity: 0.5, unit: 'tsp' },
      { name: 'Black Pepper', quantity: 0.25, unit: 'tsp' },
    ],
    instructions: [
      'Toast sourdough slices in a toaster or skillet until golden and crisp.',
      'Cut avocado, remove pit, and mash flesh in a bowl with lemon juice, salt, and pepper.',
      'Bring a small pot of water to a gentle simmer with a drop of vinegar, create a gentle whirlpool, and crack eggs in to poach for 3 minutes.',
      'Spread mashed avocado generously over warm toast slices.',
      'Carefully top each slice with a drained poached egg, season with red pepper flakes and freshly cracked black pepper.',
    ],
    nutrition: { calories: 380, protein: 16, carbs: 32, fat: 22 },
  },
  {
    title: 'Overnight Berry Chia Oats',
    description: 'Hearty rolled oats infused with almond milk, chia seeds, pure maple syrup, and topped with vibrant fresh blueberries and raspberries.',
    image: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800&q=80',
    category: 'Breakfast',
    tags: ['Vegan', 'Vegetarian', 'Healthy', 'Quick Meals', 'Low Carb'],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Rolled Oats', quantity: 1, unit: 'cups' },
      { name: 'Almond Milk', quantity: 1.5, unit: 'cups' },
      { name: 'Chia Seeds', quantity: 2, unit: 'tbsp' },
      { name: 'Maple Syrup', quantity: 2, unit: 'tbsp' },
      { name: 'Vanilla Extract', quantity: 1, unit: 'tsp' },
      { name: 'Blueberries', quantity: 0.5, unit: 'cups' },
      { name: 'Raspberries', quantity: 0.5, unit: 'cups' },
    ],
    instructions: [
      'In a medium bowl or mason jars, combine rolled oats, chia seeds, almond milk, maple syrup, and vanilla extract.',
      'Stir vigorously until chia seeds are evenly distributed and not clumped at the bottom.',
      'Seal tightly with lids and refrigerate for at least 4 hours, preferably overnight.',
      'Before serving, give oats a good stir and top with generous handfuls of fresh blueberries and raspberries.',
    ],
    nutrition: { calories: 310, protein: 9, carbs: 54, fat: 8 },
  },
  {
    title: 'Fluffy Banana Protein Pancakes',
    description: 'Golden, naturally sweet banana pancakes loaded with whey protein, wholesome rolled oats, and served with pure maple syrup.',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
    category: 'Breakfast',
    tags: ['High Protein', 'Vegetarian', 'Quick Meals'],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Ripe Banana', quantity: 2, unit: 'pieces' },
      { name: 'Eggs', quantity: 2, unit: 'pieces' },
      { name: 'Oat Flour', quantity: 1, unit: 'cups' },
      { name: 'Protein Powder', quantity: 1, unit: 'cups' },
      { name: 'Baking Powder', quantity: 1, unit: 'tsp' },
      { name: 'Cinnamon', quantity: 0.5, unit: 'tsp' },
      { name: 'Butter', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Mash ripe bananas in a large mixing bowl until smooth.',
      'Whisk in the eggs until frothy and well incorporated.',
      'Add oat flour, protein powder, baking powder, and ground cinnamon; stir gently into a thick batter.',
      'Melt a knob of butter in a non-stick skillet over medium heat.',
      'Pour batter in 1/4-cup rounds and cook for 2-3 minutes until bubbles form, then flip and cook for 2 minutes until golden.',
    ],
    nutrition: { calories: 420, protein: 32, carbs: 52, fat: 10 },
  },
  {
    title: 'Mediterranean Chickpea Crunch Bowl',
    description: 'Crisp cucumbers, juicy cherry tomatoes, kalamata olives, tangy feta cheese, and tender spiced chickpeas tossed in lemon oregano vinaigrette.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80',
    category: 'Lunch',
    tags: ['Vegetarian', 'Healthy', 'Quick Meals', 'High Protein'],
    prepTime: 15,
    cookTime: 0,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Chickpeas', quantity: 1, unit: 'cans' },
      { name: 'Cucumber', quantity: 1, unit: 'pieces' },
      { name: 'Cherry Tomatoes', quantity: 1, unit: 'cups' },
      { name: 'Red Onion', quantity: 0.5, unit: 'pieces' },
      { name: 'Kalamata Olives', quantity: 0.5, unit: 'cups' },
      { name: 'Feta Cheese', quantity: 0.5, unit: 'cups' },
      { name: 'Olive Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Lemon Juice', quantity: 2, unit: 'tbsp' },
      { name: 'Dried Oregano', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Rinse and thoroughly drain the canned chickpeas.',
      'Dice cucumber and halve cherry tomatoes. Finely slice the red onion.',
      'In a large mixing bowl, combine chickpeas, cucumber, cherry tomatoes, red onion, and kalamata olives.',
      'Whisk together olive oil, fresh lemon juice, dried oregano, salt, and black pepper in a small jar.',
      'Pour vinaigrette over bowl, toss gently, and crumble fresh feta cheese on top right before serving.',
    ],
    nutrition: { calories: 410, protein: 15, carbs: 42, fat: 21 },
  },
  {
    title: 'Grilled Lemon Herb Chicken Rice Bowl',
    description: 'Juicy marinated chicken breast seared to golden perfection, served over fragrant jasmine rice with steamed broccoli and lemon wedges.',
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&q=80',
    category: 'Lunch',
    tags: ['High Protein', 'Healthy', 'Non-Vegetarian'],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: 'Medium',
    ingredients: [
      { name: 'Chicken Breast', quantity: 2, unit: 'pieces' },
      { name: 'Jasmine Rice', quantity: 1, unit: 'cups' },
      { name: 'Broccoli', quantity: 1, unit: 'pieces' },
      { name: 'Olive Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Lemon Juice', quantity: 2, unit: 'tbsp' },
      { name: 'Garlic', quantity: 3, unit: 'cloves' },
      { name: 'Dried Thyme', quantity: 1, unit: 'tsp' },
      { name: 'Salt', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Rinse jasmine rice, add 1.75 cups water with a pinch of salt, and cook on low heat covered for 15 minutes.',
      'Whisk olive oil, lemon juice, minced garlic, thyme, salt, and pepper in a shallow dish.',
      'Pound chicken breasts to even thickness, coat thoroughly with marinade, and rest for 10 minutes.',
      'Heat a grill pan or cast-iron skillet over medium-high heat and sear chicken for 6-7 minutes per side until 165°F internal temperature.',
      'Cut broccoli into florets and steam for 4 minutes until vibrant green and tender-crisp.',
      'Slice rested chicken and arrange over fluffy rice with steamed broccoli and lemon slices.',
    ],
    nutrition: { calories: 520, protein: 48, carbs: 54, fat: 12 },
  },
  {
    title: 'Quinoa Power Bowl with Tahini Drizzle',
    description: 'Fluffy rainbow quinoa, roasted sweet potatoes, crisp chickpeas, massaged kale, and creamy garlic tahini sauce.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    category: 'Lunch',
    tags: ['Vegan', 'Vegetarian', 'Healthy', 'High Protein'],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: 'Medium',
    ingredients: [
      { name: 'Quinoa', quantity: 1, unit: 'cups' },
      { name: 'Sweet Potato', quantity: 1, unit: 'pieces' },
      { name: 'Kale', quantity: 2, unit: 'cups' },
      { name: 'Tahini', quantity: 3, unit: 'tbsp' },
      { name: 'Olive Oil', quantity: 1, unit: 'tbsp' },
      { name: 'Garlic', quantity: 1, unit: 'cloves' },
      { name: 'Lemon Juice', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C). Peel and cube sweet potato, toss in olive oil and roast for 25 minutes.',
      'Simmer rinsed quinoa in 2 cups of water for 15 minutes until tender and liquid is absorbed.',
      'Chop kale into bite-sized ribbons and massage with a drop of olive oil until tender.',
      'Whisk tahini with lemon juice, grated garlic, and warm water until a smooth drizzle forms.',
      'Assemble bowls with warm quinoa, roasted sweet potatoes, and kale; finish with generous tahini sauce.',
    ],
    nutrition: { calories: 460, protein: 14, carbs: 68, fat: 16 },
  },
  {
    title: 'Creamy Garlic Tomato Basil Pasta',
    description: 'Al dente penne pasta coated in a luxurious sun-ripened tomato basil sauce with garlic cream and shaved parmesan cheese.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d628169e?w=800&q=80',
    category: 'Dinner',
    tags: ['Vegetarian', 'Quick Meals'],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Penne Pasta', quantity: 1, unit: 'lb' },
      { name: 'Crushed Tomatoes', quantity: 1, unit: 'cans' },
      { name: 'Heavy Cream', quantity: 0.5, unit: 'cups' },
      { name: 'Garlic', quantity: 4, unit: 'cloves' },
      { name: 'Olive Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Fresh Basil', quantity: 0.5, unit: 'cups' },
      { name: 'Parmesan Cheese', quantity: 0.5, unit: 'cups' },
      { name: 'Salt', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Bring a large pot of salted water to a rolling boil and cook penne pasta until al dente; reserve 1/2 cup pasta water.',
      'In a wide skillet, heat olive oil over medium heat and sauté minced garlic for 1 minute until fragrant.',
      'Pour in crushed tomatoes, season with salt and pepper, and simmer gently for 10 minutes.',
      'Lower heat, stir in heavy cream and fresh torn basil leaves until smooth and velvety.',
      'Toss drained pasta into sauce with grated parmesan, adding reserved pasta water as needed for a glossy coating.',
    ],
    nutrition: { calories: 540, protein: 18, carbs: 72, fat: 20 },
  },
  {
    title: 'Paneer Butter Masala & Basmati Rice',
    description: 'Tender paneer cubes simmered in a silky, rich makhani gravy of ripe tomatoes, butter, aromatic spices, and paired with basmati rice.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&q=80',
    category: 'Dinner',
    tags: ['Vegetarian', 'High Protein'],
    prepTime: 20,
    cookTime: 25,
    servings: 3,
    difficulty: 'Medium',
    ingredients: [
      { name: 'Paneer', quantity: 250, unit: 'g' },
      { name: 'Tomato', quantity: 4, unit: 'pieces' },
      { name: 'Onion', quantity: 2, unit: 'pieces' },
      { name: 'Butter', quantity: 3, unit: 'tbsp' },
      { name: 'Heavy Cream', quantity: 0.25, unit: 'cups' },
      { name: 'Garlic', quantity: 4, unit: 'cloves' },
      { name: 'Ginger', quantity: 1, unit: 'tbsp' },
      { name: 'Garam Masala', quantity: 1, unit: 'tsp' },
      { name: 'Basmati Rice', quantity: 1.5, unit: 'cups' },
    ],
    instructions: [
      'Cook basmati rice with 3 cups of water and a pinch of salt until grains are separate and fluffy.',
      'Sauté chopped onions, ginger, and garlic in 1 tbsp butter, then add chopped tomatoes and cook until soft.',
      'Cool tomato mixture slightly and blend into a silk-smooth puree.',
      'Melt remaining butter in skillet, add pureed gravy, garam masala, and simmer on low for 8 minutes.',
      'Add paneer cubes and cream, simmer for 4 minutes until warm, and serve alongside piping hot basmati rice.',
    ],
    nutrition: { calories: 590, protein: 22, carbs: 58, fat: 30 },
  },
  {
    title: 'Honey Garlic Glazed Salmon',
    description: 'Crispy skin-on salmon fillets seared and glazed in a sticky, sweet-savory honey soy garlic sauce with sesame seeds.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80',
    category: 'Dinner',
    tags: ['High Protein', 'Quick Meals', 'Healthy', 'Non-Vegetarian'],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Salmon Fillets', quantity: 2, unit: 'pieces' },
      { name: 'Honey', quantity: 3, unit: 'tbsp' },
      { name: 'Soy Sauce', quantity: 2, unit: 'tbsp' },
      { name: 'Garlic', quantity: 3, unit: 'cloves' },
      { name: 'Olive Oil', quantity: 1, unit: 'tbsp' },
      { name: 'Sesame Seeds', quantity: 1, unit: 'tsp' },
      { name: 'Green Onion', quantity: 2, unit: 'stalks' },
    ],
    instructions: [
      'Pat salmon fillets dry with paper towels and season with salt and pepper.',
      'Whisk honey, soy sauce, and minced garlic together in a small ramekin.',
      'Heat olive oil in a non-stick skillet over medium-high heat until shimmering.',
      'Place salmon skin-side down and sear undisturbed for 4-5 minutes until crispy.',
      'Flip fillets, pour in honey garlic sauce, and baste continuously for 3 minutes as glaze thickens.',
      'Garnish with toasted sesame seeds and thinly sliced green onions.',
    ],
    nutrition: { calories: 480, protein: 38, carbs: 24, fat: 26 },
  },
  {
    title: 'Crispy Tofu & Rainbow Veggie Stir-Fry',
    description: 'Golden pan-crisped tofu cubes tossed with crisp bell peppers, snap peas, and broccoli in a savory ginger soy stir-fry sauce.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
    category: 'Dinner',
    tags: ['Vegan', 'Vegetarian', 'Healthy', 'Quick Meals'],
    prepTime: 15,
    cookTime: 15,
    servings: 3,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Firm Tofu', quantity: 400, unit: 'g' },
      { name: 'Bell Pepper', quantity: 2, unit: 'pieces' },
      { name: 'Broccoli', quantity: 1, unit: 'pieces' },
      { name: 'Soy Sauce', quantity: 3, unit: 'tbsp' },
      { name: 'Sesame Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Cornstarch', quantity: 1, unit: 'tbsp' },
      { name: 'Ginger', quantity: 1, unit: 'tbsp' },
      { name: 'Garlic', quantity: 2, unit: 'cloves' },
    ],
    instructions: [
      'Press tofu with a heavy skillet to remove excess moisture, cut into 1-inch cubes, and dust in cornstarch.',
      'Heat sesame oil in a wok or large pan; fry tofu cubes until all sides are deep golden and crunchy (8 mins). Remove.',
      'In same wok, toss sliced bell pepper, broccoli florets, minced garlic, and ginger over high heat for 4 minutes.',
      'Whisk soy sauce with 2 tbsp water, pour into wok, and return crispy tofu.',
      'Toss vigorously for 1-2 minutes until vegetables are glazed and tender-crisp.',
    ],
    nutrition: { calories: 340, protein: 19, carbs: 22, fat: 20 },
  },
  {
    title: 'Comforting Red Lentil Dahl',
    description: 'Creamy spiced Indian red lentils simmered with coconut milk, turmeric, cumin, cumin seeds, and fresh baby spinach.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
    category: 'Dinner',
    tags: ['Vegan', 'Vegetarian', 'Healthy', 'Budget Friendly', 'High Protein'],
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Red Lentils', quantity: 1.5, unit: 'cups' },
      { name: 'Coconut Milk', quantity: 1, unit: 'cans' },
      { name: 'Tomato', quantity: 2, unit: 'pieces' },
      { name: 'Onion', quantity: 1, unit: 'pieces' },
      { name: 'Garlic', quantity: 3, unit: 'cloves' },
      { name: 'Turmeric', quantity: 1, unit: 'tsp' },
      { name: 'Cumin', quantity: 1, unit: 'tsp' },
      { name: 'Spinach', quantity: 2, unit: 'cups' },
      { name: 'Olive Oil', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Heat olive oil in a deep saucepot and sauté diced onion and minced garlic until translucent.',
      'Add turmeric and cumin, stirring for 30 seconds until intensely aromatic.',
      'Add diced tomatoes, rinsed red lentils, coconut milk, and 2.5 cups of water; bring to a boil.',
      'Reduce heat to low, cover, and gently simmer for 20 minutes until lentils dissolve into a creamy stew.',
      'Fold in baby spinach until wilted, season with sea salt, and ladle into bowls.',
    ],
    nutrition: { calories: 370, protein: 18, carbs: 48, fat: 12 },
  },
  {
    title: 'Fresh Guacamole & Crudité Plate',
    description: 'Chunky handmade guacamole with ripe avocados, lime juice, cilantro, jalapeño, and served with crisp raw vegetable sticks.',
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=800&q=80',
    category: 'Snacks',
    tags: ['Vegan', 'Vegetarian', 'Quick Meals', 'Healthy', 'Low Carb'],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Ripe Avocado', quantity: 2, unit: 'pieces' },
      { name: 'Lime Juice', quantity: 2, unit: 'tbsp' },
      { name: 'Tomato', quantity: 1, unit: 'pieces' },
      { name: 'Red Onion', quantity: 0.25, unit: 'pieces' },
      { name: 'Fresh Cilantro', quantity: 2, unit: 'tbsp' },
      { name: 'Carrot', quantity: 2, unit: 'pieces' },
      { name: 'Cucumber', quantity: 1, unit: 'pieces' },
      { name: 'Salt', quantity: 0.5, unit: 'tsp' },
    ],
    instructions: [
      'Scoop avocado flesh into a mortar or bowl and coarsely mash with lime juice and salt.',
      'Finely dice the tomato, red onion, and fresh cilantro leaves.',
      'Fold diced vegetables into the mashed avocado gently to keep nice texture.',
      'Cut carrots and cucumber into crunchy dipper sticks.',
      'Serve fresh guacamole chilled with crisp vegetable sticks.',
    ],
    nutrition: { calories: 260, protein: 4, carbs: 20, fat: 21 },
  },
  {
    title: 'Greek Yogurt Berry Crunch Parfait',
    description: 'Thick, creamy Greek yogurt layered with artisan granola, mixed forest berries, chia seeds, and raw wildflower honey.',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
    category: 'Snacks',
    tags: ['Vegetarian', 'High Protein', 'Quick Meals', 'Healthy'],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Greek Yogurt', quantity: 1, unit: 'cups' },
      { name: 'Granola', quantity: 0.5, unit: 'cups' },
      { name: 'Blueberries', quantity: 0.25, unit: 'cups' },
      { name: 'Strawberries', quantity: 0.25, unit: 'cups' },
      { name: 'Honey', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Spoon half of the Greek yogurt into a clear glass or bowl.',
      'Add a layer of sliced strawberries, blueberries, and crunchy granola.',
      'Top with remaining Greek yogurt, more berries, and finish with a warm honey drizzle.',
    ],
    nutrition: { calories: 320, protein: 22, carbs: 42, fat: 8 },
  },
  {
    title: 'Baked Apple Cinnamon Crisp',
    description: 'Tender spiced honeycrisp apple slices baked under a golden brown buttery oat and pecan streusel crumble.',
    image: 'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=800&q=80',
    category: 'Dessert',
    tags: ['Vegetarian', 'Budget Friendly'],
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Apples', quantity: 4, unit: 'pieces' },
      { name: 'Rolled Oats', quantity: 1, unit: 'cups' },
      { name: 'Butter', quantity: 4, unit: 'tbsp' },
      { name: 'Brown Sugar', quantity: 0.25, unit: 'cups' },
      { name: 'Cinnamon', quantity: 1.5, unit: 'tsp' },
      { name: 'Lemon Juice', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Preheat oven to 350°F (175°C). Lightly grease an 8-inch baking dish.',
      'Peel and slice apples into thin wedges; toss with lemon juice, 1/2 tsp cinnamon, and 1 tbsp brown sugar.',
      'In a bowl, mix rolled oats, remaining brown sugar, cinnamon, and cut in cold butter until coarse crumbs form.',
      'Spread apple slices evenly across baking dish and scatter oat crumble generously on top.',
      'Bake for 35 minutes until apples are bubbling tender and topping is crunchy golden brown.',
    ],
    nutrition: { calories: 290, protein: 4, carbs: 46, fat: 12 },
  },
  {
    title: 'Dark Chocolate Avocado Mousse',
    description: 'Decadent, silky smooth vegan chocolate mousse whipped from velvety ripe avocados, dark Dutch cocoa, and pure maple syrup.',
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&q=80',
    category: 'Dessert',
    tags: ['Vegan', 'Vegetarian', 'Healthy', 'Quick Meals'],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      { name: 'Ripe Avocado', quantity: 2, unit: 'pieces' },
      { name: 'Cocoa Powder', quantity: 0.5, unit: 'cups' },
      { name: 'Maple Syrup', quantity: 0.33, unit: 'cups' },
      { name: 'Almond Milk', quantity: 0.25, unit: 'cups' },
      { name: 'Vanilla Extract', quantity: 1, unit: 'tsp' },
      { name: 'Salt', quantity: 0.25, unit: 'tsp' },
    ],
    instructions: [
      'Scoop ripe avocado flesh directly into a food processor or high-speed blender.',
      'Add dark cocoa powder, maple syrup, almond milk, vanilla extract, and pinch of salt.',
      'Blend on high for 2 minutes, scraping down sides once, until glossy and luxuriously smooth.',
      'Portion into dessert glasses and chill in refrigerator for 30 minutes before enjoying.',
    ],
    nutrition: { calories: 280, protein: 5, carbs: 36, fat: 16 },
  },
];
